# Generated by Django 5.0.1 on 2024-06-22 20:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={},
        ),
        migrations.RenameField(
            model_name="event",
            old_name="title",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="event",
            name="content",
        ),
        migrations.RemoveField(
            model_name="event",
            name="created_on",
        ),
        migrations.RemoveField(
            model_name="event",
            name="event_image",
        ),
        migrations.AddField(
            model_name="event",
            name="description",
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="end_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="event",
            name="image_url",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="start_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
