# Generated by Django 5.0.1 on 2024-06-22 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_alter_event_options_rename_title_event_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="end_date",
        ),
    ]
