# Generated by Django 5.0.1 on 2024-02-01 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_event_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
