# Generated by Django 5.0.1 on 2024-02-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_todolist_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='name',
            field=models.CharField(default='test', max_length=200),
        ),
        migrations.AlterOrderWithRespectTo(
            name='item',
            order_with_respect_to='todolist',
        ),
    ]
