# Generated by Django 5.0.6 on 2024-09-01 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
