# Generated by Django 3.2.10 on 2024-01-27 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=150)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('booking_date', models.DateField()),
                ('guest_number', models.IntegerField(default='')),
                ('message', models.TextField(blank=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('booked', 'Booked')], default='draft', max_length=10)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_names', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
