# Generated by Django 3.2.10 on 2024-01-12 17:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_book_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='location',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
