# Generated by Django 5.0.1 on 2024-02-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='guest_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
