# Generated by Django 5.0.1 on 2024-02-01 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_remove_booking_status_booking_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='name',
        ),
    ]
