# Generated by Django 5.0.1 on 2024-02-02 15:23

import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_remove_booking_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='guest_number',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='location',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='message',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='username',
        ),
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=150)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('booking_date', models.DateField()),
                ('guest_number', models.IntegerField(default='')),
                ('message', models.TextField(blank=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'order_with_respect_to': 'location',
            },
        ),
    ]
