# Generated by Django 5.0.1 on 2024-02-02 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_remove_booking_booking_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='booking',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='booking.booking'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='item',
            order_with_respect_to=None,
        ),
    ]
